var enText = [
  "KIRMIK Intelligent Video Analytics (KIVA) SoC is our company’s next and Al supported solution for smart city applications including an image processor (ISP) with 4k image processing capability, a 4 TOPS neural network processing engine (NPU), and a H.265 Video Codec. KIVA SoC is target to be manufactured on TSMC 22nm technology.",
  "ÇENTİK is a 32-bit RISC-V based microcontroller with peripherals like UART, SPI, I2C, PWM targeting low-cost control systems like home appliances, motor control, robotics, human machine interface. It is targeted to be manufactured on TSMC 55nm technology.",
  "YONGA FPGA takes its power from the ecosystem provided by the OSFPGA foundation and the flexible architecture brought by the OpenFPGA framework. In this way, all software and tool support can be provided for the FPGA architectures to be developed. YONGA-FPGA is Turkey’s first FPGA chip and is designed to meet a great need with its features that can meet the general needs of the Turkish industry.",
  "* DVB-RCS/RCS2 Turbo Encoder and Decoder IP Cores are based on high performance forward error correction (FEC) designs from Yongatek team compliant with ETSI EN 301 790 and ETSI EN 301 545 standards. The IP Cores use 8/16-state duo-binary Convolutional Turbo Code (CTC) with error correction performance near Shannon limit.\n* DVB-S2/X LDPC Encoder and Decoder IP Cores are based on high performance forward error correction (FEC) designs from Yongatek team compliant with ETSI EN 302 307 and ETSI EN 302 307-2 standards. The IP Cores use LDPC block codes providing error-correcting performance near Shannon limit with low complexity and flexible hardware design.",
  "Avcı Ammunation Velocity and Coordinate Identificator: AVCI İS designed for the defense industry , shooting sports and training industry. It is integrated with linescan cameras. This cutting-edge product is engineered to revolutionize the measurement of ammunition speed and coordinates, providing unparalleled accuracy and efficiency. Accuracy is vital for evaluating ammunition performance, optimizing training exercises, and enhancing overall operational efficiency.",
  "Electro-optical surveillance and tracking system is a highly optical-mechanical-electro integrated system equipped with a HD 1080p 30× daylight camera and an LWIR thermal camera. The system is mainly applied for ground and air target search and observation, able to output video and image in real time and track targets, which is widely deployed in military and civil application of police and warning.",
  "ADAS framework is a generic and scalable software platform supporting energy-efficient deployment of AI algorithms on the multicore heterogeneous computation technologies. It supports all technology solutions, including localised and distributed computation settings as well as cloud offloading. It addresses resource allocation at runtime and hybrid coherent operation with optimised task allocation at design time.",
  "KIRMIK 1.0 SoC is a video SoC product manufactured with TSMC 65nm technology, which includes our in-house developed H.264 Codec Video IP and an open-source RISC-V 64-bit Linux-capable processor. KIRMIK, the first chip developed for video applications in Turkey, is equipped with Gbit Ethernet, SD-Card, UART interfaces.",
  "Countera is a fish farming solution to count various species and various sizes of fishes on the field. Our product countera can easily be integrated onto existing fish farming tools like grading machines and fish pumps. Countera has been designed to work on various fish farming environments such as cages. Ease of use and ability to connect to the cloud-based systems makes Countera perfect solution for modern industrial applications. AI assisted image processing algorithm was specially designed for the Countera to eliminate any kind of error.",
  "“DIGITAL TAG SYSTEM” project is aimed to completely prevent LOST, LEAK, STOLEN in all retail areas and especially in merchandising operations, and to carry out all operational activities online with information processing technologies.\nElectronic shelf label, is an e-ink display device mainly placed on the shelf-edge, that replaces the traditional paper price label are getting popular nowadays. Digital Tag System attaches these energy efficient displays to the security tags while improving their existing security functions and applying additional innovative operational capabilities to traditional tags. Every Digital Tag is connected to the DES database through wireless network and displays the latest price information of the items accurately in real time. Instantly meeting dynamic pricing needs such as instant campaigns, price changes, multiple purchase discounts, DES helps you renew your business model with its cloud-integrated shelf labeling system.",
];

var trText = [
  "KIRMIK Akıllı Video Analitiği (KIVA) SoC, şirketimizin akıllı şehir uygulamaları için bir sonraki ve yapay zeka destekli çözümüdür. Bu çözüm, 4K görüntü işleme yetenekli bir görüntü işlemci (ISP), 4 TOPS sinir ağı işlem motoru (NPU) ve bir H.265 Video Kod Çözücü içerir. KIVA SoC, TSMC'nin 22nm teknolojisinde üretilmeye yöneliktir.",
  "ÇENTİK, ev aletleri, motor kontrolü, robotik, insan-makine arayüzü gibi düşük maliyetli kontrol sistemlerine yönelik, UART, SPI, I2C, PWM gibi çevre birimleri bulunan 32-bit RISC-V tabanlı bir mikrodenetleyicidir. TSMC'nin 55nm teknolojisinde üretilmeye yöneliktir.",
  "YONGA FPGA, OSFPGA vakfı tarafından sağlanan ekosistem ve OpenFPGA çerçevesi tarafından sunulan esnek mimari sayesinde gücünü alır. Bu şekilde, geliştirilecek FPGA mimarileri için tüm yazılım ve araç desteği sağlanabilir.\nYONGA-FPGA, Türkiye'nin ilk FPGA yongası olup, Türk endüstrisinin genel ihtiyaçlarını karşılayabilen özellikleriyle büyük bir ihtiyacı karşılamak üzere tasarlanmıştır.",
  "DVB-RCS/RCS2 Turbo Kodlayıcı ve Kod Çözücü IP Çekirdekleri, Yongatek ekibi tarafından tasarlanan yüksek performanslı ileri hata düzeltme (FEC) tasarımlarına dayanır ve ETSI EN 301 790 ve ETSI EN 301 545 standartlarına uygundur. IP çekirdekleri, Shannon sınırına yakın hata düzeltme performansı sağlayan 8/16 durumlu ikili-konvolüsyonel turbo kod (CTC) kullanır.\n\nDVB-S2/X LDPC Kodlayıcı ve Kod Çözücü IP Çekirdekleri, Yongatek ekibi tarafından tasarlanan yüksek performanslı ileri hata düzeltme (FEC) tasarımlarına dayanır ve ETSI EN 302 307 ve ETSI EN 302 307-2 standartlarına uygundur. IP çekirdekleri, düşük karmaşıklık ve esnek donanım tasarımıyla Shannon sınırına yakın hata düzeltme performansı sağlayan LDPC blok kodları kullanır.",
  "Avcı Mühimmat Hızı ve Koordinat Belirleyici: AVCI, savunma endüstrisi, atıcılık sporları ve eğitim endüstrisi için tasarlanmıştır. Hat tarama kameraları ile entegre edilmiştir. Bu son teknoloji ürün, mühimmat hızı ve koordinatlarının ölçümünü devrim yapacak şekilde tasarlanmış olup, eşsiz doğruluk ve verimlilik sunar. Doğruluk, mühimmat performansının değerlendirilmesi, eğitim çalışmalarının optimize edilmesi ve genel operasyonel verimliliğin artırılması için hayati önem taşır.",
  "Elektro-optik gözetim ve takip sistemi, HD 1080p 30× günlük kamerası ve bir LWIR termal kamerasıyla donatılmış yüksek optik-mekanik-elektro entegre bir sistemdir. Bu sistem, genellikle yer ve hava hedeflerinin aranması ve gözlemlenmesi için kullanılır ve hedefleri gerçek zamanlı olarak izleyebilme özelliğine sahiptir. Askeri ve polis ile uyarı gibi sivil uygulamalarda yaygın olarak kullanılmaktadır. Aynı zamanda video ve görüntü çıkışı yapabilme yeteneği de bulunmaktadır.",
  "ADAS (Advanced Driver Assistance Systems) çerçevesi, çok çekirdekli heterojen hesaplama teknolojilerinde enerji verimli bir şekilde yapay zeka algoritmalarının uygulanmasını destekleyen genel ve ölçeklenebilir bir yazılım platformudur. Bu çerçeve, yerelleştirilmiş ve dağıtılmış hesaplama ayarları ile bulut üzerindeki iş yükünü dâhil olmak üzere tüm teknoloji çözümlerini destekler. Runtimeda kaynak tahsisi ve tasarım zamanında optimize edilmiş görev atanması ile hibrit tutarlı işlemi ele alır.",
  "KIRMIK 1.0 SoC, TSMC'nin 65nm teknolojisiyle üretilen bir video SoC ürünüdür. Bu SoC ürünü, şirket içi geliştirilmiş H.264 Codec Video IP ve açık kaynaklı RISC-V tabanlı 64-bit Linux uyumlu bir işlemci içerir. Türkiye'de video uygulamaları için geliştirilen ilk çip olan KIRMIK, Gbit Ethernet, SD-Kart ve UART arabirimleriyle donatılmıştır.",
  "Countera, sahada çeşitli türler ve farklı boyutlardaki balıkları saymak için bir balık çiftçiliği çözümüdür. Ürünümüz Countera, kolaylıkla derecelendirme makineleri ve balık pompaları gibi mevcut balık çiftçiliği araçlarına entegre edilebilir. Countera, kafes gibi çeşitli balık çiftçiliği ortamlarında çalışmak üzere tasarlanmıştır. Bulut tabanlı sistemlere bağlanma kolaylığı ve kullanım kolaylığı, Countera'yı modern endüstriyel uygulamalar için mükemmel bir çözüm haline getirir. AI destekli görüntü işleme algoritması, Countera için her türlü hatayı ortadan kaldırmak üzere özel olarak tasarlanmıştır.",
  "DIJİTAL ETİKET SİSTEMİ projesi, perakende alanlarında ve özellikle ürün yönetimi işlemlerinde, KAYIP, SIZMA ve ÇALINTI olaylarını tamamen önlemeyi ve tüm operasyonel faaliyetleri bilgi işleme teknolojileri ile çevrimiçi olarak gerçekleştirmeyi hedeflemektedir.\n\nElektronik raf etiketi, geleneksel kağıt fiyat etiketlerinin yerine ana olarak raf kenarına yerleştirilen e-mürekkep (e-ink) ekran cihazıdır ve günümüzde popülerlik kazanmaktadır. Dijital Etiket Sistemi, bu enerji verimli ekranları güvenlik etiketlerine eklerken mevcut güvenlik fonksiyonlarını geliştirir ve geleneksel etiketlere ek olarak ek yenilikçi operasyonel yetenekler uygular. Her Dijital Etiket, kablosuz ağ aracılığıyla DES (Digital Etiket Sistemi) veritabanına bağlanır ve ürünlerin en güncel fiyat bilgisini gerçek zamanlı olarak doğru bir şekilde görüntüler. Anlık kampanyalar, fiyat değişiklikleri, çoklu satın alma indirimleri gibi dinamik fiyatlandırma ihtiyaçlarını hızlı bir şekilde karşılamak için DES, bulut entegrasyonlu raf etiketleme sistemi ile iş modelinizi yenilemenize yardımcı olur.",
];

var name = [
  "KİRMİK 2.0",
  "CENTİK",
  "FPGA",
  "SATCOM",
  "AVCİ",
  "İZCİ",
  "ADAS",
  "KİRMİK 1.0",
  "COUNTERA",
  "DES",
];